kind: Service
apiVersion: v1
metadata:
  name: blog-webhook-service
  namespace: blog
  labels:
    app: blog-webhook
spec:
  selector:
    app: blog-webhook
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30090
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-webhook
  namespace: blog
  labels:
    app: blog-webhook
spec:
  replicas: 1
  revisionHistoryLimit: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-webhook
      annotations:
        kubernetes.io/change-cause: "FIXME"
    spec:
      containers:
      - name: blog-webhook
        image: asia.gcr.io/fe-tmaki/blog-webhook:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: cloud,kubernetes
        - name: _JAVA_OPTIONS
          value: "-Xmx45M -Xss1M -XX:MaxMetaspaceSize=99M -XX:ReservedCodeCacheSize=32M -XX:CompressedClassSpaceSize=18M -XX:MaxDirectMemorySize=32M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP"
        - name: SECURITY_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: ops-username
        - name: SECURITY_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: ops-password
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              name: blog-webhook-config
              key: vcap-application.json
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              name: blog-webhook-config
              key: vcap-services.json
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
